services:
  database:
    image: "postgres:16.0-alpine3.18" # alpine is lightest images
    env_file:
      - ../.env
    ports:
      - "5432:5432" # expose the container port "host:container" where host is the port of our machine and container is the container port we want to expose
